<?php
    require("views/encabezado_view.phtml");
?>
    <h4 class="col-md-12">Registrar un cliente</h4>

    <?php
		echo '<form class="form-horizontal" action="'.$index.'" method="POST">';
	?>
		<div class="form-group">
			<label class="control-label col-sm-2">Nombre Completo</label>
			<div class="col-sm-10">
				<input class="form-control" type="text" name="nombre_alta" id="input_nombrealta">
			</div>
		</div>
		<div class="form-group">
			<label class="control-label col-sm-2" for="pwd">Teléfono</label>
			<div class="col-sm-10">
				<input class="form-control" type="number" name="tfno_alta" id="input_tfnoalta">
			</div>
		</div>
		<div class="form-group"> 
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-success" id="boton_registrar" disabled>Registrar</button>
			</div>
		</div>
	</form>

	<div class="row">
		<?php
			unset($_POST['seleccion']);
	        unset($_POST['id']);
			echo '<form action="'.$index.'" method="POST">';
		?>
			<div class="form-group"> 
				<div class="col-sm-offset-2 col-sm-10">
		        <input class="btn btn-default" type="submit" value="Volver">
			</div>
		</form>
	</div>
<?php
    require("views/footer_view.phtml");
?>