<?php
    require("views/encabezado_view.phtml");
?>
<div class="row">
    <h4>Resultados de la búsqueda <?php echo $_POST['busqueda'] ?></h4>
</div>
<div class="row">
    <table class="table table-striped table-hover">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Teléfono</th>
            <th colspan="3">Acciones</th>
        </tr>
        <?php
            $index = "index.php";

            foreach ($encontrados as $encontrado) {
                echo "<tr><td>". $encontrado["id"]."</td>";
                echo "<td>". $encontrado["nombre"]."</td>";
                echo "<td>". $encontrado["telefono"]."</td>";

                echo 
                    '<td>
                        <form action="'.$index.'" method="POST">
                            <input class="btn btn-info" type="submit" value="Ver Contactos">
                            <input type="hidden" name="seleccion" value="contactos">
                            <input type="hidden" name="id" value="'.$encontrado["id"].'">
                        </form>
                    </td>';

                echo 
                    '<td>
                        <form action="'.$index.'" method="POST">
                            <input class="btn btn-danger" type="submit" value="Borrar">
                            <input type="hidden" name="seleccion" value="borrar">
                            <input type="hidden" name="id" value="'.$encontrado["id"].'">
                        </form>
                    </td>';

                echo 
                    '<td>
                        <form action="'.$index.'" method="POST">
                            <input class="btn btn-warning" type="submit" value="Modificar">
                            <input type="hidden" name="seleccion" value="modificar">
                            <input type="hidden" name="id" value="'.$encontrado["id"].'">
                        </form>
                    </td></tr>';
            }
        ?>
    </table>
    <?php
        unset($_POST['seleccion']);
        unset($_POST['id']);
        echo '
            <form action="'.$index.'" method="POST">
                <input class="btn btn-default" type="submit" value="Volver">
            </form>';
    ?>
<?php
    require("views/footer_view.phtml");
?>