<?php
    require("views/encabezado_view.phtml");
?>
<div class="row">
    <h4>Listado Clientes</h4>
</div>
<?php
    echo '<form class="form-inline" action="'.$index.'" method="POST">'
?>  
    <div class="row col-md-4 pull-right" id="searchbar">
        <div class="form-group">
            <input type="text" class="form-control" name="busqueda" id="input_busqueda" placeholder="&#x1F50D;&#09;Buscar..">
            <input type="hidden" name="seleccion" value="buscar">
        </div>
        <button type="submit" class="btn btn-default" id="boton_buscar" disabled>Buscar</button>
    </div>
</form>
<div class="row">
    <table class="table table-striped table-hover">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Teléfono</th>
            <th colspan="3">Acciones</th>
        </tr>
        <?php
            $index = "index.php";

            foreach ($datos as $dato) {
                echo "<tr id='row_".$dato["id"]."'><td>". $dato["id"]."</td>";
                echo "<td id=ncli".$dato["id"]."'>". $dato["nombre"]."</td>";
                echo "<td>". $dato["telefono"]."</td>";

                echo 
                    '<td>
                        <form action="'.$index.'" method="POST">
                            <input class="btn btn-info" type="submit" value="Ver Contactos">
                            <input type="hidden" name="seleccion" value="contactos">
                            <input type="hidden" name="id" value="'.$dato["id"].'">
                        </form>
                    </td>';

                echo 
                    '<td>
                        <form action="'.$index.'" method="POST">
                            <input class="borrar_cliente btn btn-danger" type="submit" value="Borrar">
                            <input type="hidden" name="seleccion" value="borrar">
                            <input type="hidden" name="id" value="'.$dato["id"].'">
                        </form>
                    </td>';

                echo 
                    '<td>
                        <form action="'.$index.'" method="POST">
                            <input class="modificar_cliente btn btn-warning" type="submit" value="Modificar">
                            <input type="hidden" name="seleccion" value="modificar">
                            <input type="hidden" name="id" value="'.$dato["id"].'">
                        </form>
                    </td></tr>';
            }
        ?>
    </table>

    <p class="text-warning"><span class="glyphicon glyphicon-warning-sign"></span> - Aviso: Pulsar en "Borrar" borrará permanentemente el cliente y todos sus contactos asociados</p>

    <?php
        echo '<form class="form-inline" action="'.$index.'" method="POST">'
    ?>  
        <button type="submit" class="btn btn-primary">Alta nuevo Cliente</button>
        <input type="hidden" name="seleccion" value="alta">
    </form>
</div>
<?php
    require("views/footer_view.phtml");
?>