<?php
    require("views/encabezado_view.phtml");
?>
<div class="row">
    <h4>Contactos</h4>
</div>
<div class="row">
    <table class="table table-striped table-hover" id="lista_contactos">
        <thead>
            <tr>
                <th>ID contacto</th>
                <th>ID referente</th>
                <th>Nombre</th>
                <th>Teléfono</th>
                <th colspan="2">Acciones</th>
            </tr>
        </thead>
        <tbody>
        <?php
            foreach ($contactos as $contacto) {
                echo "<tr id='row_".$contacto["id_contacto"]."'><td>". $contacto["id_contacto"]."</td>";
                echo "<td>". $contacto["id_referente"]."</td>";
                echo "<td>". $contacto["nombre"]."</td>";
                echo "<td>". $contacto["telefono"]."</td>";

                echo 
                    '<td>
                        <form action="'.$index.'" method="POST">
                            <button class="borrar_contacto btn btn-danger" type="submit"><span class="glyphicon glyphicon-trash"></span> Borrar</button>
                            <input type="hidden" name="seleccion" value="borrar_contacto">
                            <input type="hidden" name="id_contacto" value="'.$contacto["id_contacto"].'">
                        </form>
                    </td>';

                echo 
                    '<td>
                        <form action="'.$index.'" method="POST">
                            <button class="modificar_contacto btn btn-warning" type="submit"><span id="span_guardar" class="glyphicon glyphicon-pencil"></span> Modificar</button>
                            <input type="hidden" name="seleccion" value="modificar_contacto">
                            <input type="hidden" name="id_contacto" value="'.$contacto["id_contacto"].'">
                        </form>
                    </td></tr>';
            }
        ?>
        </tbody>
    </table>

    <p class="text-warning"><span class="glyphicon glyphicon-warning-sign"></span> - Aviso: Pulsar en "Borrar" borrará el contacto de forma permanente.</p>

    <div class="form-group"> 
        <button id="btn_addcontacto" class="btn btn-primary"><span class="glyphicon glyphicon-user"></span> Añadir contacto</button>
    </div>

    <div id="div_contactoform" class="row form-group">
        <?php
            echo '
                <input type="hidden" id="id_referente" value="'.$_POST['id'].'">
            ';

        ?>
    </div>

    <?php
        echo '
            <form action="'.$index.'" method="POST">
                <input class="btn btn-default" type="submit" value="Volver">
            </form>';
    ?>

</div>
<?php
    require("views/footer_view.phtml");
?>