<?php
    require("views/encabezado_view.phtml");
?>
<div class="row">
    <h4>Contactos</h4>
</div>
<div class="row">
    <table class="table table-striped table-hover">
        <tr>
            <th>ID contacto</th>
            <th>ID referente</th>
            <th>Nombre</th>
            <th>Teléfono</th>
            <th colspan="2">Acciones</th>
        </tr>
        <?php
            foreach ($contactos as $contacto) {
                echo "<tr><td>". $contacto["id_contacto"]."</td>";
                echo "<td>". $contacto["id_referente"]."</td>";
                echo "<td>". $contacto["nombre"]."</td>";
                echo "<td>". $contacto["telefono"]."</td>";

                echo 
                    '<td>
                        <form action="'.$index.'" method="POST">
                            <input class="btn btn-danger" type="submit" value="Borrar">
                            <input type="hidden" name="seleccion" value="borrar_contacto">
                            <input type="hidden" name="id_contacto" value="'.$contacto["id_contacto"].'">
                        </form>
                    </td>';

                echo 
                    '<td>
                        <form action="'.$index.'" method="POST">
                            <input class="btn btn-warning" type="submit" value="Modificar">
                            <input type="hidden" name="seleccion" value="modificar_contacto">
                            <input type="hidden" name="id_contacto" value="'.$contacto["id_contacto"].'">
                        </form>
                    </td></tr>';
            }
        ?>
    </table>

    <div class="form-group"> 
        <button id="btn_addcontacto" class="btn btn-primary"><span class="glyphicon glyphicon-user"></span> Añadir contacto</button>
    </div>

    <div id="div_contactoform">
        
    </div>

    <?php
        unset($_POST['seleccion']);
        unset($_POST['id']);
        echo '
            <form action="'.$index.'" method="POST">
                <input class="btn btn-default" type="submit" value="Volver">
            </form>';
    ?>

</div>
<?php
    require("views/footer_view.phtml");
?>