<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="css/style.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="JQuery/jquery-3.3.1.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="JQuery/clientes.js"></script>

        <title>Clientes</title>
    </head>
    <body>
        <?php
            // Variable global
            $index = "index.php";
        ?>
        <div class="container">
            
            <h2 class="col-md-12"><span class="glyphicon glyphicon-link"></span> Aplicación Clientes</h2>
            