<?php
    require("views/encabezado_view.phtml");
?>
    <h4 class="col-md-12">Modificar datos cliente</h4>

    <?php
		echo '<form class="form-horizontal" action="'.$index.'" method="POST">';
	?>
		<div class="form-group">
			<label class="control-label col-sm-2">Nuevo nombre</label>
			<div class="col-sm-10">
				<input class="form-control" type="text" name="nuevo_nombre" id="input_modnombre">
			</div>
		</div>
		<div class="form-group">
			<label class="control-label col-sm-2" for="pwd">Nuevo teléfono</label>
			<div class="col-sm-10"> 
				<input class="form-control" type="number" name="nuevo_tfno" id="input_modtfno">
			</div>
		</div>
		<div class="form-group"> 
			<div class="col-sm-offset-2 col-sm-10">
				<?php
					echo '<input type="hidden" name="id" value="'.$_POST['id'].'">';
				?>
				<button type="submit" class="btn btn-warning" id="boton_mod">Modificar</button>
			</div>
		</div>
	</form>

	<div class="row">
		<?php
			unset($_POST['seleccion']);
	        unset($_POST['id']);
			echo '<form action="'.$index.'" method="POST">';
		?>
			<div class="form-group"> 
				<div class="col-sm-offset-2 col-sm-10">
		        <input class="btn btn-default" type="submit" value="Volver">
			</div>
		</form>
	</div>
<?php
    require("views/footer_view.phtml");
?>